language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $TRAVIS_CI_TOKEN
  keep_history: true
  repo: coolgod/coolgod.github.io
  target_branch: master
  on:
    branch: master